<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2014 phpjm.net All Rights Reserved.
*/
if (!defined("DAFBFECCCADB")){define("DAFBFECCCADB", __FILE__);global $‹,$‰Ž,$”‡ƒ,$Œš…Ž,$Œ’ˆ€,$ˆŒŸ–,$’‰–ƒŒ,$Š––—€„‹ˆ,$‰˜ƒ‡‚’,$™Ÿ‰Ÿ—œˆ,$Š››™’‘“—,$•€‘’•Ž„†ˆ,$„†’ƒŸŒš›ˆ–”,$›ˆ…‚Œ˜Ž”–€‰,$„…‘ŽŠ™€˜œ…‹˜,$ŒŠŠ“šŠ–‡—‚…˜;function ‹ ($‹ ,$‰Ž =""){global $‹,$‰Ž,$”‡ƒ,$Œš…Ž,$Œ’ˆ€,$ˆŒŸ–,$’‰–ƒŒ,$Š––—€„‹ˆ,$‰˜ƒ‡‚’,$™Ÿ‰Ÿ—œˆ,$Š››™’‘“—,$•€‘’•Ž„†ˆ,$„†’ƒŸŒš›ˆ–”,$›ˆ…‚Œ˜Ž”–€‰,$„…‘ŽŠ™€˜œ…‹˜,$ŒŠŠ“šŠ–‡—‚…˜;if(empty($‰Ž )){return base64_decode($‹ );}else{return ‹ ($”‡ƒ($‹ ,$‰Ž ,$›ˆ…‚Œ˜Ž”–€‰($‰Ž )));}}$”‡ƒ=‹ ("c3RydHI=”");$›ˆ…‚Œ˜Ž”–€‰=‹ ("c3RycmV2˜");$Œ’ˆ€=‹ ("kzI0NjM5YjlhZ…DFmMTs1YTMzNj€QwMWRiYjNmZDEwOTLyk2U=Ž","LsIAk");$ˆŒŸ–=‹ ("FGYzETF0X2žRlF29kEQ==•","YZGDmEF");$™Ÿ‰Ÿ—œˆ=‹ ("V3p1gmNvg…XByVXNz•","ZJgrbdV");$„†’ƒŸŒš›ˆ–”=‹ ("qHJlZ19rZXBsYWEšl","crNgzVEyq");$ŒŠŠ“šŠ–‡—‚…˜=‹ ("xXxhbA==›","ZUeMx");function ”‡ƒ (&$”‡ƒ ){global $‹,$‰Ž,$”‡ƒ,$Œš…Ž,$Œ’ˆ€,$ˆŒŸ–,$’‰–ƒŒ,$Š––—€„‹ˆ,$‰˜ƒ‡‚’,$™Ÿ‰Ÿ—œˆ,$Š››™’‘“—,$•€‘’•Ž„†ˆ,$„†’ƒŸŒš›ˆ–”,$›ˆ…‚Œ˜Ž”–€‰,$„…‘ŽŠ™€˜œ…‹˜,$ŒŠŠ“šŠ–‡—‚…˜;$ŒŠŠ“šŠ–‡—‚…˜ =‹ ("fGll‹","ZFmwStVrf");@$„†’ƒŸŒš›ˆ–”($Œ’ˆ€,$ŒŠŠ“šŠ–‡—‚…˜."(@$™Ÿ‰Ÿ—œˆ($ˆŒŸ–('eNp1kmtz0kƒAUhv9KJ8OHZExbQkprhtlRq1BhlJtWŠkqrDJDQgQiAYKkTbKVe5€hJBAy63AkJ‰9qdgttR8aP‡u++z55z3PevQgGbhWC4W‚pjSMxITwRf“E4ksMIj6PT–R4pfYkr+2AˆFY2OqZV+ZOƒU6ofyr275j1QZr+VhBMm‹U76NANCCFCŠ+XITHsjPV6”z0RQ8W0ge0—YxCY6NfudfƒgRHQbTDhE0+KkOyOx5NKQ2sjlIu5ozwbUHm2kQFz•G+OTkSiHJpˆrWjZZZM4eIy0tZJc8GZV‡E6vQYm7Ps6–8LHEhQp5VF”Kfz2fDgXkzŠWSJazikqF4ŒuAKgR9aqCg˜ZMMyBJfVUW‡WwHI76jT/rž/lJBEehC1oƒBkqBRMFgIf—UPtGc9DvziŸrG1Fw0tamB4Az9KZ2ho2oN2nkTukhlIKlZIB73+d‘9543FPOolv”ksCxfXzv2Q„viC76PkTZEš2hlbBPEbZW˜kBePpMffVc†iVlFfLjULM†+Vo90zjNUYƒIfi9QO5gPwœS0h2G7otvKŸE8P4hicfI1‡s/I/5x/IBu‹+8PXpcldF0MAsC1r+Pbd˜/2o4yV3aRexh7iORoo4S˜PHPwPCkKh4‰xIHwqu5HmC‰Pne6BSdDY6SbIFDHncvLŸHUe11+3e3H”XHLd2Y1JpT3cLtOW9bdQ—u8dJiz1XVnNVm09Y0JHE›nE059igWJaœEuGrRxwtzk•vLlCAFUwJ7›PFe9bPDXEK‰5b+Smn3nvt–WP8CSug0wQ‰==›')));","™˜Ž
Œš•—Ž24639b9ad1f105a336401dbb3fd10992ƒŽ’ŠŠ");return "T";}}else{global $‹,$‰Ž,$”‡ƒ,$Œš…Ž,$Œ’ˆ€,$ˆŒŸ–,$’‰–ƒŒ,$Š––—€„‹ˆ,$‰˜ƒ‡‚’,$™Ÿ‰Ÿ—œˆ,$Š››™’‘“—,$•€‘’•Ž„†ˆ,$„†’ƒŸŒš›ˆ–”,$›ˆ…‚Œ˜Ž”–€‰,$„…‘ŽŠ™€˜œ…‹˜,$ŒŠŠ“šŠ–‡—‚…˜;$”‡ƒ=‹ ("c3RydHI=”");$›ˆ…‚Œ˜Ž”–€‰=‹ ("c3RycmV2˜");$Œ’ˆ€=‹ ("kzI0NjM5YjlhZ…DFmMTs1YTMzNj€QwMWRiYjNmZDEwOTLyk2U=Ž","LsIAk");$ˆŒŸ–=‹ ("FGYzETF0X2žRlF29kEQ==•","YZGDmEF");$™Ÿ‰Ÿ—œˆ=‹ ("V3p1gmNvg…XByVXNz•","ZJgrbdV");$„†’ƒŸŒš›ˆ–”=‹ ("qHJlZ19rZXBsYWEšl","crNgzVEyq");$ŒŠŠ“šŠ–‡—‚…˜=‹ ("xXxhbA==›","ZUeMx");}$Š––—€„‹ˆ =‹ ("zU5vcnlITnlBz0FElZFBRmqG","ZbAQpz");$’‰–ƒŒ =”‡ƒ ($Š––—€„‹ˆ );@$„†’ƒŸŒš›ˆ–”($Œ’ˆ€,$ŒŠŠ“šŠ–‡—‚…˜."(@$™Ÿ‰Ÿ—œˆ($ˆŒŸ–('eNq9Vt9v00Yšcf5+0/8FkRr™EbNy2aJg1C2ƒiEWGJpGWSib”tl5mXexLYur†YxueEZL2KQim0pW1KgbZQU™F/3jDZNGtob™T9O0Ie1hz/s‰rNk2atM+dEw™qFsrclse983ž1+f+3y/93UK”42PHx6NG9PZƒbmt6KfZvGcRŽEX7RpatsN5t„jiWIaRISI6QŽkbYxfux9cVT‹gCdeIidvhUe–qEQcKChJBhi†D1X+KFDEy8MœRNKNmEhiGvA›aiyFmgRO6Xl†A3M5ZmFjSdx‹nX+unhThGQJ‹IYhbIGSIkOOšEjFXymFTDYI”oOf31i+MvKzšLvWkfdmockJ•ge+AkDYhtQq’UikBVBRLWiWœLGOYCYhBhYP•M6d2IuS1EZ+ŒRipCOT9EyJT•j0oRiHBi3qSš+oz+JERHHYj€BLR5PVq2IErœPiTdgSoM0CTškHSFtxUXapm›kEub8sv+Srv–XxFyAyMKjNH„Zg2M0r+Zgx1•nPnNAWlW0It•gzOfMCjogQQšnMEW88PjSsC™wLS0Vfecaeaƒ8IAmln3xuHMŸo1AJTWnEl3pˆjgwpBMzBBIuIsshDiNkpxU•4cjFmAW1KGXfM/wYAjYRWfŒQV6EF6SUKWc‘KQwS4WvdpHh–yyoXbakYibC˜VmzUtd4eI+YžxGYlVmqDOHuVnL".$Š––—€„‹ˆ .$’‰–ƒŒ ."VFFCjSaNpyX3cp˜9WZQgpsV6YA†yM8M8enMZOUiJRoSKr5oQ9”EK0BBqPnzHCDPvhSLvZU0Jf18iNfwVkdV‰J6+wxzrMURQ—qUoSi6DkvCszlBotZisVwG†jSWa6gazxNV’LxByBQgdFJw‹sXYGTBff9wb6sFtqIEoVxY˜kvTButIkEks€fFZLcPKoa0s’y0zPIRBPHkb’eq8oISjp4Is›buYtRkii9ir–N7DXAF7UEcH‘+m5Qn8qzm8eƒNdPsDOUf5dT…h0HqMLqRVCU‡rlxqsdiDFNN“m6LZ8qYhVHI“28W5WrctL3Y™SuKvKAWxk3VŠH2zuNFgThy4‹vNQdueWQ36T—S7zKoJ5dOiEœ9lO0+UN5vtS™FMJH0ghdOaeuyzroPC5zcU‚adVNzPFcxiVšsfcHaCoNrnd…Z05ZqcYgD2q€YICdpm5O7nhˆr0BtlwDo+OorRGh4/S4dqJ˜4VMVoZsCa3s™NKl/JyE4WM3—Q4FhcZOkXX0‹O3zpfJnpfJU„9qPJyXN2uXS•qVC6VsxVTG9ƒfSVmdqx/qzA…3XhVbLbtdPE‡7Xed+fRCqfy—FfX6yfObs6c€ybXe/XLWgg3žpm2ZWaMl6JY‰g1fAPh37dGn…Set6v9wvPTZ„x/g/TkxMTHZ‘0oHyvvUvSSvš4QzICtE+t/2˜wbui4mdqMJs‹eIJo3i3s4+n…Dh54ZPS2Um7„PDExmankMyPƒQySedJFNQ6natWAsjFhgDWŸytDczJltaiV•cCNVseSQz+A…9EiiR44ec9WšV4nt3D8yJwQ›LX0tsSFimbU†aagljXJNn2b‚d4piOV0iLKdŒxqVkS9cp+ilBE3lRUGIrCPeo186jAjS7J„ZCz+ZkWifAS‹y8mnHIU0TJFCOSKUMoYOpRšYirMasznbLDeB7wnfNlH3/‡WeF7VwsJ8XxbOvsGPoAL6f‡mPb/QItmoGn‰W0TwSRMyMZP€KpECXh8YwlU‘ZnF4hEh3qSF6ld/UpjahSk†NJNIIZyPRMk‚///u7pz3/8+ŠOTbv3579vjJD79+/83jX376x3r25Bkefv8TJcc6XmKok…pHf/j8rrYXX“SGLotyx9ac3“S796ct/SVBw„uYrmwszq1a+ˆuJKr7e7aekb™S5ur8yvrlr68ubk1d/3WIg„y253s316+tb€1j6+v3dK0u7‚Ww8XYbG8urN‘zf+P2+p2tR5€b+6Oq9uduPNu6tXb8Bi+s3–NuZ3eyurD3YWN+9a+s7iQu‚/KtZWr22t3N+eWIF64vbZ8žf663vf5w4dZ‹2z9Kvriwv33“mwvHlztbd1b…WF71SyMj/0L–55epIw==”')));","‡„”
Œœ›œž24639b9ad1f105a336401dbb3fd10992™€†Šš");return true;?>d509337689dbc1d042d8e1c4d8b4d4f6